server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db_second
    username: root
    password: Navya@2809
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
  boot:
  message: hello-world
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
