server:
  port: 6666
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: Navya@2809
  jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
         dialect:
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/           
  
